services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # 【魔法の仕掛け】Linuxのfrontendフォルダと、コンテナ内の/appフォルダを四次元ポケットで繋ぐ
      - ./frontend:/app
      # ただし、部品(node_modules)だけはコンテナ専用のものを使うという除外設定
      - /app/node_modules
    # 開発環境用の設定
    environment:
      - NODE_ENV=development